// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT-Y8fjQuiQISC2sKOZduwRoJSwlOIwNY',
    appId: '1:16799825350:web:29fa814d444a22d6ba46c7',
    messagingSenderId: '16799825350',
    projectId: 'runaar-82048',
    authDomain: 'runaar-82048.firebaseapp.com',
    storageBucket: 'runaar-82048.firebasestorage.app',
    measurementId: 'G-62BGQJ6SLS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyZGO-iVzn_UKnb8swOPqtNteRiTQSevk',
    appId: '1:16799825350:android:39f68d3dbe895967ba46c7',
    messagingSenderId: '16799825350',
    projectId: 'runaar-82048',
    storageBucket: 'runaar-82048.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCH1wnJcoJjVlol70yW2Ga-qHTnqc9Fso',
    appId: '1:16799825350:ios:dc999f625e783739ba46c7',
    messagingSenderId: '16799825350',
    projectId: 'runaar-82048',
    storageBucket: 'runaar-82048.firebasestorage.app',
    iosBundleId: 'com.example.runaar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCH1wnJcoJjVlol70yW2Ga-qHTnqc9Fso',
    appId: '1:16799825350:ios:dc999f625e783739ba46c7',
    messagingSenderId: '16799825350',
    projectId: 'runaar-82048',
    storageBucket: 'runaar-82048.firebasestorage.app',
    iosBundleId: 'com.example.runaar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAT-Y8fjQuiQISC2sKOZduwRoJSwlOIwNY',
    appId: '1:16799825350:web:5ed45e8b1297e2c0ba46c7',
    messagingSenderId: '16799825350',
    projectId: 'runaar-82048',
    authDomain: 'runaar-82048.firebaseapp.com',
    storageBucket: 'runaar-82048.firebasestorage.app',
    measurementId: 'G-738EJF82BC',
  );
}
